//定义错误类型
const NAME_OR_PASSWORD_IS_REQUIRED='NAME_OR_PASSWORD_IS_REQUIRED'
const USER_ALREADY_EXISTS='USER_ALREADY_EXISTS'



module.exports={
    NAME_OR_PASSWORD_IS_REQUIRED,
    USER_ALREADY_EXISTS,
}


