//定义错误类型
const NAME_OR_PASSWORD_IS_REQUIRED='NAME_OR_PASSWORD_IS_REQUIRED'
const USER_ALREADY_EXISTS='USER_ALREADY_EXISTS'
const USER_NOT_EXISTS='USER_NOT_EXISTS'
const PASSWORD_ERROR='PASSWORD_ERROR'



module.exports={
    NAME_OR_PASSWORD_IS_REQUIRED,
    USER_ALREADY_EXISTS,
    USER_NOT_EXISTS,
    PASSWORD_ERROR
}


